version: '3.8'

volumes:
  nginxdata:
    driver: local

services:
  nginx:
    image: nginx:${NGINX_VERSION:-1.19}-alpine
    container_name: nginx
    ports:
      - 80:80
    env_file:
      - .env.development
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginxdata:/var/cache/nginx/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
    container_name: web
    restart: always
    env_file:
      - .env.development
