version: '3.8'

volumes:
  nginxdata:
    driver: local

services:
  nginx-front:
    image: nginx:${NGINX_VERSION:-1.19}-alpine
    ports:
      - 80:80
    env_file:
      - .env.development
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginxdata:/var/cache/nginx/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
    restart: always
    env_file:
      - .env.development
    ports:
      - ${WEB_PORT:-3000}:3000
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./firebase.json:/app/firebase.json
      - ./public:/app/public
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./next.config.js:/app/next.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
