version: '3.8'

volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
  nginxdata:
    driver: local

services:
  db:
    image: mysql:${MYSQL_VERSION:-8.0.27}
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.development
    ports:
      - 3306:3306
  redis:
    image: redis:${REDIS_VERSION:-7.0.4}
    restart: always
    volumes:
      - redisdata:/data
  nginx:
    image: nginx:${NGINX_VERSION:-1.19}-alpine
    ports:
      - 80:80
    env_file:
      - .env.development
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginxdata:/var/cache/nginx/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
    restart: always
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
