version: '3.8'

volumes:
  nginxdata:
    driver: local

networks:
  strapinetwork:
    name: strapinetwork
    external: true

services:
  nginx:
    image: nginx:${NGINX_VERSION:-1.19}-alpine
    ports:
      - 8080:80
      - 8081:81
    env_file:
      - .env.development
    environment:
      STRAPI_SUPERADMIN_HOSTING_PORT: 80
      STRAPI_MANAGER_HOSTING_PORT: 81
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginxdata:/var/cache/nginx/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - strapi-superadmin
      - strapi-manager
  strapi-superadmin:
    container_name: strapi-superadmin
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
    restart: unless-stopped
    env_file: .env.development
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_NAME: strapi
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env.development:/opt/app/.env
      - ./.gitignore:/opt/app/.gitignore
    ports:
      - 1337:1337
      - 1340:8000
    networks:
      - strapinetwork
  strapi-manager:
    container_name: strapi-manager
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
    restart: unless-stopped
    env_file: .env.development
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_NAME: strapi
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    ports:
      - 1338:1337
      - 1339:1339
    networks:
      - strapinetwork
