version: '3.8'

volumes:
  nginxdata:
    driver: local

services:
  nginx-strapi:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION:-1.19}
    image: ${ECR_REGISTRY}/${ECR_STRAPI_NGINX_REPOSITORY}:${NGINX_VERSION:-1.19}-${ENV:-dev}-${TAG:-latest}
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - strapi-superadmin
      - strapi-manager
  strapi-superadmin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
        - NODE_ENV=${NODE_ENV:-production}
    image: ${ECR_REGISTRY}/${ECR_STRAPI_ADMIN_REPOSITORY}:${NODE_VERSION:-16.14.2}-${ENV:-dev}-${TAG:-latest}
    restart: unless-stopped
    env_file: .env
    ports:
      - 1337:1337
  strapi-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
        - NODE_ENV=${NODE_ENV:-production}
    image: ${ECR_REGISTRY}/${ECR_STRAPI_APP_REPOSITORY}:${NODE_VERSION:-16.14.2}-${ENV:-dev}-${TAG:-latest}
    restart: unless-stopped
    env_file: .env
    ports:
      - 1338:1337
      - 1339:1338
